name: "CI"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checking out"
      uses: actions/checkout@v1

    - name: "Building docker image"
      run: docker build -t georchestra/ssh_data .

    - name: "Pushing image to docker hub"
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker push georchestra/ssh_data
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: "Update Docker Hub Description for SSH Data"
      if: github.ref == 'refs/heads/master' && github.repository == 'georchestra/sshdata' && github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: georchestra/ssh_data
        readme-filepath: ./DOCKER_HUB.md
        short-description: 'SSH data module for the geOrchestra SDI'