name: "CI"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checking out"
      uses: actions/checkout@v1

    - name: "Building docker image"
      run: docker build -t georchestra/sshdata .

    - name: "Pushing image to docker hub"
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker push georchestra/sshdata
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}